# Generated by Django 5.2.17 on 2026-09-18 23:27

import apps.accounts.managers
import apps.accounts.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE SEQUENCE accounts_user_id_seq "
                "AS BIGINT START WITH 1 INCREMENT BY 1 "
                "MINVALUE 1 MAXVALUE 9999999999 NO CYCLE"
            ),
            reverse_sql="DROP SEQUENCE IF EXISTS accounts_user_id_seq",
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(editable=False, max_length=14, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[apps.accounts.validators.validate_e164_phone_number])),
                ('phone_country_code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='invalid_country_code', message='Use a two-letter uppercase ISO country code.', regex='^[A-Z]{2}$')])),
                ('date_of_birth', models.DateField(validators=[apps.accounts.validators.validate_date_not_in_future])),
                ('password', models.CharField(db_column='credential_hash', max_length=255, verbose_name='credential hash')),
                ('credential_kind', models.CharField(choices=[('PIN', 'PIN'), ('PASSWORD', 'Password')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('id', ''), _negated=True), name='users_id_not_empty'), models.CheckConstraint(condition=models.Q(('password', ''), _negated=True), name='users_credential_hash_not_empty'), models.CheckConstraint(condition=models.Q(('credential_kind__in', ['PIN', 'PASSWORD'])), name='users_credential_kind_valid'), models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='users_email_ci_unique')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='accounts.refreshtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refresh_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='refresh_user_exp_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='refresh_expiry_after_creation'), models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('created_at')), _connector='OR'), name='refresh_revoked_after_creation'), models.CheckConstraint(condition=models.Q(('replaced_by__isnull', True), ('revoked_at__isnull', False), _connector='OR'), name='refresh_replacement_is_revoked'), models.CheckConstraint(condition=models.Q(('id', models.F('replaced_by_id')), _negated=True), name='refresh_cannot_replace_itself')],
            },
        ),
    ]
